services:
  - type: web
    name: ordinals  # Your service name
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir
    startCommand: python ordinals.py  # Your script file
